name: TalentTree
favicon: null
layout_spectrum: 0.9872853902634233
typography_spectrum: 0.5541241210885346
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.10795245016925037
  lightness: 0.32281140168197453
  saturation: 0.10797714255750179
  rhythmicContrast: 0.8094007077161223
purpose: []
